### ISSUE TITLE
flutter_bloc 9.0.0 compatibility

### ISSUE THREAD

**Issue by Konst80** [Iteo/hooked_bloc#85]
Please add compatibility with flutter_bloc 9.0.0.

Currently it is not possible to use flutter_bloc 9.0.0 with hooked_bloc 1.5.0. 

Output by flutter pub get:

`Resolving dependencies...
Because hooked_bloc 1.5.0 depends on flutter_bloc ^8.1.3 and no versions of hooked_bloc match >1.5.0 <2.0.0, hooked_bloc ^1.5.0 requires flutter_bloc ^8.1.3...`

**Comment by westito** [comment]
I created a PR request for that. Until merge, you can use git ref
```yaml
dependencies:
  hooked_bloc:
    git: git@github.com:westito/hooked_bloc.git
```
